version: "2"

issues:
  max-same-issues: 0

formatters:
  enable:
    - goimports
    - gofmt

  settings:
    goimports:
      local-prefixes:
        - github.com/autobrr/upbrr

linters:
  enable:
    - copyloopvar
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - gocritic
    - gosec
    - loggercheck
    - mirror
    - misspell
    - perfsprint
    - prealloc
    - rowserrcheck
    - spancheck
    - testifylint
    - unconvert
    - unused
    - whitespace

  disable:
    - containedctx
    - noctx
    - revive

  settings:
    exhaustive:
      default-signifies-exhaustive: false

    misspell:
      ignore-rules:
        - alltime
        - hardlink
        - hardlinked

    gosec:
      excludes:
        - G115

  exclusions:
    generated: lax

    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - path: _test\.go
        linters:
          - gosec
      - path: internal/clients/search\.go
        text: G402
        linters:
          - gosec
      - path: internal/config/config\.go
        text: G117
        linters:
          - gosec
